In [2]:
import pandas as pd

In [3]:
df = pd.read_csv('dengue_PR.csv.gz')

df.head()

         date  SE     casos  diff_casos  casos_mean  casos_std  casos_slope
0  2010-01-24   4  7.784715    0.416670    7.243636   0.364523     0.313907
1  2010-01-31   5  8.188735    0.404020    7.570653   0.465085     0.415953
2  2010-02-07   6  8.741296    0.552561    8.020698   0.507233     0.452377
3  2010-02-14   7  9.185855    0.444559    8.475151   0.532604     0.475598
4  2010-02-21   8  9.684223    0.498367    8.950027   0.551768     0.493102

In [4]:
df = pd.read_csv('/Users/eduardoaraujo/Documents/Github/ensemble_curto_prazo_updated/data/dengue_PR.csv.gz')

df.head()

         date  SE     casos  diff_casos  casos_mean  casos_std  casos_slope
0  2010-01-24   4  7.784715    0.416670    7.243636   0.364523     0.313907
1  2010-01-31   5  8.188735    0.404020    7.570653   0.465085     0.415953
2  2010-02-07   6  8.741296    0.552561    8.020698   0.507233     0.452377
3  2010-02-14   7  9.185855    0.444559    8.475151   0.532604     0.475598
4  2010-02-21   8  9.684223    0.498367    8.950027   0.551768     0.493102

In [6]:
df = pd.read_parquet('/Users/eduardoaraujo/Documents/Github/load_infodengue_data/data/cases/MG_dengue.parquet',
                    columns = ['SE', 'casos_est', 'casprov', 'municipio_geocodigo'])

df.head()

                SE  casos_est  casprov  municipio_geocodigo
data_iniSE
2010-01-03  201001        0.0      0.0              3166402
2010-01-03  201001        0.0      0.0              3100401
2010-01-03  201001        0.0      0.0              3157104
2010-01-03  201001        0.0      0.0              3131208
2010-01-03  201001        0.0      0.0              3145877

In [7]:
df.to_parquet('MG_dengue.parquet')